version: "3.3"

services:
  essenlive:
    build:
      context: ./
      dockerfile: Dockerfile
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=proxy"
      - "traefik.http.routers.essenlive-secure.entrypoints=websecure"
      - "traefik.http.routers.essenlive-secure.rule=Host(`perso.essenlive.xyz`)"
      - "traefik.http.services.essenlive-service.loadbalancer.server.port=3000"
    networks:
      - proxy
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
      - /usr/src/app/.next
    env_file:
      - .env
      
networks:
  proxy:
    external: true